import type { Metadata } from "next";
import { Geist, Geist_Mono, Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const zenKaku = Zen_Kaku_Gothic_New({
  subsets: ['latin'],
  weight: ['300','400','500','700','900'], // 使用するウェイトに応じて変更（例: 300, 400, 500, 700）
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={zenKaku.className}
      >
        {children}
      </body>
    </html>
  );
}
